In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option("display.max_colwidth", 1000)

In [102]:
# dfsmall = pd.read_csv('./data/smalldata.csv',low_memory=False, dtype={'Uri':str})
dfsmall = pd.read_csv('./data/smalldata.csv',low_memory=False)

In [105]:
mask = dfsmall['Country'] == 'USA'
dfsmall = dfsmall[mask]
dfsmall = dfsmall[['Uri','Title','Artist', 'Album/Single','Genre','Genre_new','Explicit', 
                'Release_date', 'danceability', 'energy', 'mode','speechiness','valence','tempo','duration_ms']]
dfsmall.info()

# mask  = dfsmall.Release_date.str.contains('2020')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6645 entries, 1 to 89426
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Uri           6645 non-null   object
 1   Title         6645 non-null   object
 2   Artist        6645 non-null   object
 3   Album/Single  6645 non-null   object
 4   Genre         6645 non-null   object
 5   Genre_new     6645 non-null   object
 6   Explicit      6645 non-null   object
 7   Release_date  6645 non-null   object
 8   danceability  6645 non-null   object
 9   energy        6645 non-null   object
 10  mode          6645 non-null   object
 11  speechiness   6645 non-null   object
 12  valence       6645 non-null   object
 13  tempo         6645 non-null   object
 14  duration_ms   6645 non-null   object
dtypes: object(15)
memory usage: 830.6+ KB

In [54]:
dfsmall.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6645 entries, 1 to 89426
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Uri           6645 non-null   object
 1   Title         6645 non-null   object
 2   Artist        6645 non-null   object
 3   Album/Single  6645 non-null   object
 4   Genre         6645 non-null   object
 5   Genre_new     6645 non-null   object
 6   Explicit      6645 non-null   object
 7   Release_date  6645 non-null   object
 8   danceability  6645 non-null   object
 9   energy        6645 non-null   object
 10  mode          6645 non-null   object
 11  speechiness   6645 non-null   object
 12  valence       6645 non-null   object
 13  tempo         6645 non-null   object
 14  duration_ms   6645 non-null   object
dtypes: object(15)
memory usage: 1.1+ MB

In [106]:
dfbig = pd.read_csv('./data/bigdata.csv',low_memory=False)

In [107]:
dfbig.shape

(9807001, 8)

In [108]:
mask = dfbig['country'] == 'USA'
dfbig = dfbig[mask]
dfbig.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 280200 entries, 280200 to 560399
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  280200 non-null  int64
 1   country     280200 non-null  object
 2   date        280200 non-null  object
 3   position    280200 non-null  float64
 4   uri         280200 non-null  object
 5   track       280200 non-null  object
 6   title       280200 non-null  object
 7   artist      280184 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 19.2+ MB

In [109]:
dfbig.shape

(280200, 8)

In [111]:
# mask  = dfbig.date.str.contains('2020')
dfbig.uri.nunique()

7210

In [115]:
dfbig.sample()

,Unnamed: 0,country,date,position,uri,track,title,artist
402110,402110,USA,07/03/2019,111.0,https://open.spotify.com/track/7AFASza1mXqntmGtbxXprO,"changes , XXXTENTACION",changes,XXXTENTACION

In [61]:
test = dfbig.sample().uri
test

431712    https://open.spotify.com/track/5SehvGGC53A7SZK...
Name: uri, dtype: object

In [62]:
test

431712    https://open.spotify.com/track/5SehvGGC53A7SZK...
Name: uri, dtype: object

In [63]:
print(test)

431712    https://open.spotify.com/track/5SehvGGC53A7SZK...
Name: uri, dtype: object

In [95]:
test = dfsmall.sample().Uri.to_string()

In [99]:
print(test)

5

In [161]:
dfbig.groupby(['uri'])['position'].count().sort_values()

uri
https://open.spotify.com/track/3IEHJ5lWMxExmrn2zlhcVu       1
https://open.spotify.com/track/2SCUNHTUORvAnmWjSsp5Ib       1
https://open.spotify.com/track/2SVx3uds6jTWALFxevIWMA       1
https://open.spotify.com/track/2Sla5cgNpVoRcckYjaAMKP       1
https://open.spotify.com/track/2TBQoW7s6iwKcg139ssqie       1
                                                         ...
https://open.spotify.com/track/75ZvA4QfFiZvzhj2xkaWAh    1143
https://open.spotify.com/track/7GX5flRQZVHRAGd6B4TmDO    1158
https://open.spotify.com/track/7m9OqQk4RVRkw9JJdeAw96    1167
https://open.spotify.com/track/3a1lNhkSLSkpJE4MSHpDu9    1167
https://open.spotify.com/track/6gBFPUFcJLzWGx4lenP6h2    1383
Name: position, Length: 7210, dtype: int64

In [156]:
test

1       1758
2        707
7        388
3        354
4        329
        ...
130        1
146        1
150        1
162        1
1383       1
Name: position, Length: 417, dtype: int64

In [171]:
dfbig[dfbig['position'] <= 10].groupby(['uri'])['position'].count()

uri
https://open.spotify.com/track/00ko9WaS4jOX1kEk3gvHjf      3
https://open.spotify.com/track/017PF4Q3l4DBUiWoXk4OWT      1
https://open.spotify.com/track/01TnVDiet1DFTsyWKUKovl      1
https://open.spotify.com/track/01iuzK2ziYAVE2n9aSXbWp      1
https://open.spotify.com/track/021lWIHJrURZrmvYQ1xcM8      1
                                                        ...
https://open.spotify.com/track/7yotKA30dwTKNEGomV9ZsI      7
https://open.spotify.com/track/7ytR5pFWmSjzHJIeQkgog4    164
https://open.spotify.com/track/7yyRTcZmCiyzzJlNzGC9Ol      1
https://open.spotify.com/track/7zLGHiDWd9T1Rxw4PQCb13      1
https://open.spotify.com/track/7zgqtptZvhf8GEmdsM2vp2      5
Name: position, Length: 782, dtype: int64

In [172]:
dfextra['daysintop10'] = 0
dfsmall['daysintop20'] = 0

,Uri,Title,Artist,Album/Single,Genre,Genre_new,Explicit,Release_date,danceability,energy,mode,speechiness,valence,tempo,duration_ms,daysintop10
87841,https://open.spotify.com/track/0KA5Cc68h9qitLwTadHBpa,back on,Gucci Mane,album,atl hip hop,hip hop,True,2017-10-13,0.828,0.639,1,0.163,0.4270000000000001,156.055,181533,0
37288,https://open.spotify.com/track/6klLvorLoo1sxvZcjJIY8I,make no sense,YoungBoy Never Broke Again,album,baton rouge rap,rap,True,2019-10-11,0.8759999999999999,0.733,0,0.333,0.962,154.904,148630,0
60110,https://open.spotify.com/track/6U2NuJILEOEpW2tVCuqKHb,dura - remix,Daddy Yankee - Natti Natasha - Becky G - Bad Bunny,single,latin,latin,False,2018-04-27,0.772,0.8029999999999999,1,0.0468,0.853,94.981,242160,0
570,https://open.spotify.com/track/1zmgEIHE0eXH0IhBGuoTkP,run,Joji,album,alternative r&b,r&b/soul,False,2020-09-24,0.448,0.72,1,0.0332,0.361,157.91899999999995,195000,0
85570,https://open.spotify.com/track/0frzpcv2zCUk13mn0X824T,mall,Gucci Mane,album,atl hip hop,hip hop,True,2017-12-22,0.7490000000000001,0.809,1,0.0504,0.311,147.99200000000005,167683,0
84576,https://open.spotify.com/track/1Q3HtTFGxjmEljAw7Y0CaR,options,NF,album,hip hop,hip hop,False,2019-07-26,0.8079999999999999,0.768,1,0.099,0.328,141.006,206040,0
87174,https://open.spotify.com/track/48AGUAbQ4itLXYEDAr2UZC,love,Jhené Aiko,album,alternative r&b,r&b/soul,False,2020-03-06,0.362,0.466,1,0.0858,0.339,83.944,156467,0
48602,https://open.spotify.com/track/6CeZoh6Oemi28WQRpa004x,the way,Trippie Redd - Russ,album,melodic rap,rap,True,2020-02-21,0.78,0.6659999999999999,0,0.172,0.537,145.97799999999995,243287,0
89001,https://open.spotify.com/track/7EoSDrwBPUBeBEORrpvgko,water,Ugly God,album,meme rap,rap,True,2017-08-04,0.816,0.245,0,0.414,0.187,140.04,138936,0
63094,https://open.spotify.com/track/7rTzrRdc5UbvLr0gwI1J3E,out of love,Lil Tecca - Internet Money,single,melodic rap,rap,True,2020-04-17,0.732,0.654,0,0.045,0.369,138.049,153597,0

In [201]:
a = dfbig.groupby(['uri'])['position'].min().rename('peakposition')  
b = dfbig.groupby(['uri'])['position'].count().rename('daysintop200')
c = dfbig[dfbig['position'] <= 10].groupby(['uri'])['position'].count().rename('daysintop10')
d = dfbig[dfbig['position'] <= 20].groupby(['uri'])['position'].count().rename('daysintop20')

dfextra = pd.concat([a, b,c,d],axis=1).fillna(0).reset_index()
dfextra.rename(columns={'uri':'Uri'},inplace=True)
dfextra.head()

,Uri,peakposition,daysintop200,daysintop10,daysintop20
0,https://open.spotify.com/track/000xQL6tZNLJzIrtIgxqSl,52.0,68,0.0,0.0
1,https://open.spotify.com/track/003VDDA7J3Xb2ZFlNx7nIZ,31.0,7,0.0,0.0
2,https://open.spotify.com/track/003eoIwxETJujVWmNFMoZy,57.0,10,0.0,0.0
3,https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B,150.0,60,0.0,0.0
4,https://open.spotify.com/track/007d7JT41sSc1HqWTs4uw7,197.0,1,0.0,0.0

In [197]:
dfsmall.head()

,Uri,Title,Artist,Album/Single,Genre,Genre_new,Explicit,Release_date,danceability,energy,mode,speechiness,valence,tempo,duration_ms,daysintop10
1,https://open.spotify.com/track/6FyRXC8tJUh863JCkyWqtk,adan y eva,Paulo Londra,single,argentine hip hop,hip hop,False,2018-11-05,0.767,0.7090000000000001,1,0.336,0.72,171.993,258639,0
17,https://open.spotify.com/track/5xhJmd0I15jFcEdqxfCzKk,it wont kill ya,The Chainsmokers - Louane,album,dance pop,pop,False,2017-04-07,0.5720000000000001,0.53,0,0.0654,0.12,170.138,217613,0
40,https://open.spotify.com/track/0wJJhRgdHhT93Z3iWdMB0T,hymn,Kesha,single,dance pop,pop,True,2017-08-03,0.488,0.5379999999999999,1,0.076,0.38,67.03699999999999,205600,0
59,https://open.spotify.com/track/6JSryEdVJTZq6YBn3wK2sn,arrows,Foo Fighters,album,alternative metal,metal,False,2017-09-15,0.515,0.917,1,0.0417,0.409,121.988,266187,0
81,https://open.spotify.com/track/7nAfXgeHfDO50upcOjJOaq,talking to myself,Linkin Park,album,alternative metal,metal,False,2017-05-19,0.593,0.7120000000000001,0,0.0286,0.473,124.013,231307,0

In [227]:
dfsmall.Release_date.sort_values()

85162    1942-01-01
4758     1942-01-01
50681    1944-01-01
18727    1945-01-01
11011    1945-01-01
            ...
7399     2020-10-30
85787    2020-10-30
85223    2020-10-30
5793     2020-10-30
45368    2020-11-05
Name: Release_date, Length: 6645, dtype: object

In [249]:
df = pd.merge(dfsmall, dfextra, on='Uri', how='left')
df.head()

# df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
# Traceback (most recent call last):

,Uri,Title,Artist,Album/Single,Genre,Genre_new,Explicit,Release_date,danceability,energy,mode,speechiness,valence,tempo,duration_ms,peakposition,daysintop200,daysintop10,daysintop20
0,https://open.spotify.com/track/6FyRXC8tJUh863JCkyWqtk,adan y eva,Paulo Londra,single,argentine hip hop,hip hop,False,2018-11-05,0.767,0.7090000000000001,1,0.336,0.72,171.993,258639,191.0,1,0.0,0.0
1,https://open.spotify.com/track/5xhJmd0I15jFcEdqxfCzKk,it wont kill ya,The Chainsmokers - Louane,album,dance pop,pop,False,2017-04-07,0.5720000000000001,0.53,0,0.0654,0.12,170.138,217613,55.0,7,0.0,0.0
2,https://open.spotify.com/track/0wJJhRgdHhT93Z3iWdMB0T,hymn,Kesha,single,dance pop,pop,True,2017-08-03,0.488,0.5379999999999999,1,0.076,0.38,67.03699999999999,205600,100.0,2,0.0,0.0
3,https://open.spotify.com/track/6JSryEdVJTZq6YBn3wK2sn,arrows,Foo Fighters,album,alternative metal,metal,False,2017-09-15,0.515,0.917,1,0.0417,0.409,121.988,266187,131.0,1,0.0,0.0
4,https://open.spotify.com/track/7nAfXgeHfDO50upcOjJOaq,talking to myself,Linkin Park,album,alternative metal,metal,False,2017-05-19,0.593,0.7120000000000001,0,0.0286,0.473,124.013,231307,123.0,1,0.0,0.0

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6645 entries, 0 to 6644
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Uri           6645 non-null   object
 1   Title         6645 non-null   object
 2   Artist        6645 non-null   object
 3   Album/Single  6645 non-null   object
 4   Genre         6645 non-null   object
 5   Genre_new     6645 non-null   object
 6   Explicit      6645 non-null   object
 7   Release_date  6645 non-null   object
 8   danceability  6645 non-null   object
 9   energy        6645 non-null   object
 10  mode          6645 non-null   object
 11  speechiness   6645 non-null   object
 12  valence       6645 non-null   object
 13  tempo         6645 non-null   object
 14  duration_ms   6645 non-null   object
 15  peakposition  6645 non-null   float64
 16  daysintop200  6645 non-null   int64
 17  daysintop10   6645 non-null   float64
 18  daysintop20   6645 non-null   float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.0+ MB

In [253]:
df[["danceability", "energy","mode", "speechiness","valence","tempo","duration_ms"]] = df[["danceability", "energy","mode", "speechiness","valence","tempo","duration_ms"]].apply(pd.to_numeric)
df.describe()

,danceability,energy,mode,speechiness,valence,tempo,duration_ms,peakposition,daysintop200,daysintop10,daysintop20
count,6645.000000,6645.000000,6645.000000,6645.000000,6645.000000,6645.000000,6645.000000,6645.000000,6645.000000,6645.000000,6645.000000
mean,0.678186,0.618876,0.599850,0.149661,0.458409,122.232958,204640.685929,84.341159,40.648307,1.988412,4.029646
std,0.150092,0.167939,0.489966,0.131381,0.218954,29.793435,53478.241367,58.835554,96.952518,11.618705,18.343186
min,0.125000,0.005430,0.000000,0.022900,0.026200,45.780000,30133.000000,1.000000,1.000000,0.000000,0.000000
25%,0.581000,0.515000,0.000000,0.047200,0.286000,97.022000,174444.000000,32.000000,2.000000,0.000000,0.000000
50%,0.691000,0.631000,1.000000,0.093000,0.449000,121.998000,200693.000000,76.000000,7.000000,0.000000,0.000000
75%,0.789000,0.739000,1.000000,0.230000,0.620000,144.042000,228720.000000,134.000000,32.000000,0.000000,0.000000
max,0.980000,0.996000,1.000000,0.966000,0.982000,212.058000,943529.000000,200.000000,1383.000000,206.000000,272.000000

In [255]:
df.to_csv('myspotify.csv',index=False)